/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package spdvi;

import java.awt.event.WindowEvent;


/**
 *
 * @author Alumne
 */
public class MainForm extends javax.swing.JFrame implements Runnable {
    Thread cronometroHilo;
    boolean cronometroActivo;
    boolean cronometroPausado;
    boolean cronometroIniciado = true;
    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblInfoCronometro = new javax.swing.JLabel();
        btnIniciarCronometro = new javax.swing.JButton();
        btnAturarCronometro = new javax.swing.JButton();
        btnReiniciarCronometro = new javax.swing.JButton();
        lblCronometro = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuExit = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenu2 = new javax.swing.JMenu();
        mnuInicia = new javax.swing.JMenuItem();
        mnuAtura = new javax.swing.JMenuItem();
        mnuReinicia = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cronometro");
        setResizable(false);

        lblInfoCronometro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInfoCronometro.setText("00:00:00");

        btnIniciarCronometro.setText("Inicia");
        btnIniciarCronometro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarCronometroActionPerformed(evt);
            }
        });

        btnAturarCronometro.setText("Atura");
        btnAturarCronometro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAturarCronometroActionPerformed(evt);
            }
        });

        btnReiniciarCronometro.setText("Reinicia");
        btnReiniciarCronometro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReiniciarCronometroActionPerformed(evt);
            }
        });

        lblCronometro.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblCronometro.setForeground(new java.awt.Color(51, 0, 51));
        lblCronometro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCronometro.setText("Cronometro");
        lblCronometro.setToolTipText("");
        lblCronometro.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(204, 204, 204), java.awt.Color.lightGray, null, new java.awt.Color(153, 153, 153)));
        lblCronometro.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jMenu1.setText("File");

        mnuExit.setText("Exit");
        mnuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuExitActionPerformed(evt);
            }
        });
        jMenu1.add(mnuExit);
        jMenu1.add(jSeparator1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        mnuInicia.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuInicia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Icon_Iniciar.jpg"))); // NOI18N
        mnuInicia.setText("Inicia");
        mnuInicia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuIniciaActionPerformed(evt);
            }
        });
        jMenu2.add(mnuInicia);

        mnuAtura.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuAtura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Icon_pause.png"))); // NOI18N
        mnuAtura.setText("Atura");
        mnuAtura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAturaActionPerformed(evt);
            }
        });
        jMenu2.add(mnuAtura);

        mnuReinicia.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuReinicia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Icon_Reiniciar.png"))); // NOI18N
        mnuReinicia.setText("Reinicia");
        mnuReinicia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuReiniciaActionPerformed(evt);
            }
        });
        jMenu2.add(mnuReinicia);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(lblCronometro, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(49, 49, 49)
                            .addComponent(lblInfoCronometro, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(41, 41, 41))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(btnIniciarCronometro, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnAturarCronometro, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnReiniciarCronometro, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblCronometro, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInfoCronometro, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnAturarCronometro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnReiniciarCronometro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnIniciarCronometro))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarCronometroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarCronometroActionPerformed
        iniciarCrono();
    }//GEN-LAST:event_btnIniciarCronometroActionPerformed

    private void btnAturarCronometroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAturarCronometroActionPerformed
        pausarCrono();
    }//GEN-LAST:event_btnAturarCronometroActionPerformed

    private void btnReiniciarCronometroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReiniciarCronometroActionPerformed
        reiniciarCrono();
    }//GEN-LAST:event_btnReiniciarCronometroActionPerformed

    private void mnuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuExitActionPerformed
        this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_mnuExitActionPerformed

    private void mnuIniciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuIniciaActionPerformed
        iniciarCrono();
    }//GEN-LAST:event_mnuIniciaActionPerformed

    private void mnuAturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAturaActionPerformed
        pausarCrono();
    }//GEN-LAST:event_mnuAturaActionPerformed

    private void mnuReiniciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuReiniciaActionPerformed
        reiniciarCrono();
    }//GEN-LAST:event_mnuReiniciaActionPerformed

    private void reiniciarCrono() {
        cronometroActivo = false;
        cronometroIniciado = true;
        lblInfoCronometro.setText( "00:00:00" );
    }
    
    private void pausarCrono() {
        cronometroPausado = true ;
        cronometroIniciado = true;
    }
    
    private void iniciarCrono() {
        if (cronometroIniciado) {
            cronometroHilo = new Thread(this);
            cronometroActivo = true;
            cronometroPausado = false;
            cronometroHilo.start();
            cronometroIniciado = false;
        }
    }
    @Override
    public void run() {
        Integer horas = 0, minutos = 0, segundos = 0, milesimas = 0;
        String  hour = "", min = "", seg = "", mil = "";
        try {
            while (cronometroActivo) {
                if (!cronometroPausado) {
                    Thread.sleep(1000);
                    segundos += 1;
                    if (segundos == 60){
                        segundos = 0;
                        minutos++;
                        if (minutos == 60){
                            minutos = 0;
                            horas++;
                        }
                    }
                    
                    if (horas < 10) hour = "0" + horas;
                    else hour = horas.toString();
                    if( minutos < 10 ) min = "0" + minutos;
                    else min = minutos.toString();
                    if( segundos < 10 ) seg = "0" + segundos;
                    else seg = segundos.toString();
                    lblInfoCronometro.setText(horas + ":" + min + ":" + seg  );
                }
            }
            lblInfoCronometro.setText(horas + ":" + min + ":" + seg);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAturarCronometro;
    private javax.swing.JButton btnIniciarCronometro;
    private javax.swing.JButton btnReiniciarCronometro;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JLabel lblCronometro;
    private javax.swing.JLabel lblInfoCronometro;
    private javax.swing.JMenuItem mnuAtura;
    private javax.swing.JMenuItem mnuExit;
    private javax.swing.JMenuItem mnuInicia;
    private javax.swing.JMenuItem mnuReinicia;
    // End of variables declaration//GEN-END:variables
}
